kind: pipeline
name: default

platform:
    os: linux
    arch: amd64

steps:
    - name: build_test
      image: node:16.14.0
      environment:
          CODECOV_TOKEN:
              from_secret: CODECOV_TOKEN
          SOL_AST_COMPILER_CACHE: /.compiler_cache
      commands:
          # pre-download compilers from historical builds archive
          # see https://github.com/ethereum/solc-bin
          # see https://binaries.soliditylang.org/
          - apt-get -qq update && apt-get -qq install jq
          - ./download.sh 'linux-amd64' $SOL_AST_COMPILER_CACHE
          - ./download.sh 'wasm' $SOL_AST_COMPILER_CACHE
          # perform testing
          - npm install --unsafe-perm
          - npm link --unsafe-perm
          - npm run lint
          - npm run test:ci
          - npm run coverage:upload
